Repository YAPP-Github/oksusu-susu-android, pull requests merged in 2024-02, with the labels that each got.

#114 Feature/mz 220 envelope filter UI
  feature/received/src/main/java/com/susu/feature/received/ledgerfilter/LedgerFilterScreen.kt
  feature/sent/src/main/java/com/susu/feature/envelopefilter/EnvelopeFilterContract.kt
  feature/sent/src/main/java/com/susu/feature/envelopefilter/EnvelopeFilterScreen.kt
  feature/sent/src/main/java/com/susu/feature/envelopefilter/EnvelopeFilterViewModel.kt
  feature/sent/src/main/java/com/susu/feature/envelopefilter/component/MoneySlider.kt
  feature/sent/src/main/res/values/strings.xml
Labels: feature, 🚨 ASAP

#115 Chore/google-form 피드백 남기기, 문의하기 클릭시 구글폼으로 이동
  core/ui/src/main/java/com/susu/core/ui/Consts.kt
  feature/mypage/src/main/java/com/susu/feature/mypage/main/MyPageDefaultScreen.kt
  feature/mypage/src/main/java/com/susu/feature/mypage/social/MyPageSocialScreen.kt
Labels: chore

#118 Feature/mz 144 앱 버전 업데이트 확인
  core/ui/src/main/java/com/susu/core/ui/Consts.kt
  feature/mypage/build.gradle.kts
  feature/mypage/src/main/java/com/susu/feature/mypage/main/MyPageContract.kt
  feature/mypage/src/main/java/com/susu/feature/mypage/main/MyPageDefaultScreen.kt
  feature/mypage/src/main/java/com/susu/feature/mypage/main/MyPageViewModel.kt
  feature/mypage/src/main/java/com/susu/feature/mypage/main/component/MyPageMenuItem.kt
  feature/mypage/src/main/res/values/strings.xml
  gradle/libs.versions.toml
Labels: feature

#119 Feature/ledger edit date
  feature/received/src/main/java/com/susu/feature/received/ledgeredit/LedgerEditContract.kt
  feature/received/src/main/java/com/susu/feature/received/ledgeredit/LedgerEditScreen.kt
  feature/received/src/main/java/com/susu/feature/received/ledgeredit/LedgerEditViewModel.kt
  feature/received/src/main/res/drawable/ic_date_change.xml
  feature/received/src/main/res/values/strings.xml
Labels: feature

#121 Feature/mz 135 vote edit delete report
  core/model/src/main/java/com/susu/core/model/Vote.kt
  core/model/src/main/java/com/susu/core/model/exception/SusuExceptions.kt
  data/src/main/java/com/susu/data/data/di/RepositoryModule.kt
  data/src/main/java/com/susu/data/data/repository/BlockRepositoryImpl.kt
  data/src/main/java/com/susu/data/data/repository/ReportRepositoryImpl.kt
  data/src/main/java/com/susu/data/data/repository/VoteRepositoryImpl.kt
  data/src/main/java/com/susu/data/remote/api/BlockService.kt
  data/src/main/java/com/susu/data/remote/api/ReportService.kt
  data/src/main/java/com/susu/data/remote/api/VoteService.kt
  data/src/main/java/com/susu/data/remote/di/ApiServiceModule.kt
  data/src/main/java/com/susu/data/remote/model/request/BlockUserRequest.kt
  data/src/main/java/com/susu/data/remote/model/request/EditVoteRequest.kt
  data/src/main/java/com/susu/data/remote/model/request/ReportVoteRequest.kt
  data/src/main/java/com/susu/data/remote/model/response/PopularVoteResponse.kt
  data/src/main/java/com/susu/data/remote/model/response/VoteDetailResponse.kt
  data/src/main/java/com/susu/data/remote/model/response/VoteResponse.kt
  domain/src/main/java/com/susu/domain/repository/BlockRepository.kt
  domain/src/main/java/com/susu/domain/repository/ReportRepository.kt
  domain/src/main/java/com/susu/domain/repository/VoteRepository.kt
  domain/src/main/java/com/susu/domain/usecase/block/BlockUserUseCase.kt
  domain/src/main/java/com/susu/domain/usecase/envelope/CreateReceivedEnvelopeUseCase.kt
  domain/src/main/java/com/susu/domain/usecase/envelope/EditReceivedEnvelopeUseCase.kt
  domain/src/main/java/com/susu/domain/usecase/report/ReportVoteUseCase.kt
  domain/src/main/java/com/susu/domain/usecase/vote/DeleteVoteUseCase.kt
  domain/src/main/java/com/susu/domain/usecase/vote/EditVoteUseCase.kt
  feature/community/src/main/java/com/susu/feature/community/community/CommunityContract.kt
  feature/community/src/main/java/com/susu/feature/community/community/CommunityScreen.kt
  feature/community/src/main/java/com/susu/feature/community/community/CommunityViewModel.kt
  feature/community/src/main/java/com/susu/feature/community/community/component/VoteCard.kt
  feature/community/src/main/java/com/susu/feature/community/navigation/CommunityNavigation.kt
  feature/community/src/main/java/com/susu/feature/community/votedetail/VoteDetailContract.kt
  feature/community/src/main/java/com/susu/feature/community/votedetail/VoteDetailScreen.kt
  feature/community/src/main/java/com/susu/feature/community/votedetail/VoteDetailViewModel.kt
  feature/community/src/main/java/com/susu/feature/community/votedetail/component/VoteItem.kt
  feature/community/src/main/java/com/susu/feature/community/voteedit/VoteEditContract.kt
  feature/community/src/main/java/com/susu/feature/community/voteedit/VoteEditScreen.kt
  feature/community/src/main/java/com/susu/feature/community/voteedit/VoteEditViewModel.kt
  feature/community/src/main/java/com/susu/feature/community/votesearch/VoteSearchScreen.kt
  feature/community/src/main/res/values/strings.xml
  feature/navigator/src/main/java/com/susu/feature/navigator/MainNavigator.kt
  feature/navigator/src/main/java/com/susu/feature/navigator/MainScreen.kt
  feature/received/src/main/java/com/susu/feature/received/envelopeadd/ReceivedEnvelopeAddViewModel.kt
  feature/received/src/main/java/com/susu/feature/received/envelopedetail/ReceivedEnvelopeDetailContract.kt
  feature/received/src/main/java/com/susu/feature/received/envelopedetail/ReceivedEnvelopeDetailScreen.kt
  feature/received/src/main/java/com/susu/feature/received/envelopedetail/ReceivedEnvelopeDetailViewModel.kt
  feature/received/src/main/java/com/susu/feature/received/envelopeedit/ReceivedEnvelopeEditViewModel.kt
  feature/received/src/main/java/com/susu/feature/received/ledgerdetail/LedgerDetailContract.kt
  feature/received/src/main/java/com/susu/feature/received/ledgerdetail/LedgerDetailScreen.kt
  feature/received/src/main/java/com/susu/feature/received/ledgerdetail/LedgerDetailViewModel.kt
  feature/received/src/main/java/com/susu/feature/received/ledgersearch/LedgerSearchScreen.kt
  feature/received/src/main/java/com/susu/feature/received/navigation/ReceivedNavigation.kt
Labels: feature

#120 Feature/mz 130 수수 통계
  core/designsystem/src/main/java/com/susu/core/designsystem/component/text/AnimatedCounterText.kt
  core/model/src/main/java/com/susu/core/model/SusuStatistics.kt
  data/src/main/java/com/susu/data/data/repository/StatisticsRepositoryImpl.kt
  data/src/main/java/com/susu/data/remote/api/StatisticsService.kt
  data/src/main/java/com/susu/data/remote/model/response/StatisticsResponse.kt
  domain/src/main/java/com/susu/domain/repository/StatisticsRepository.kt
  domain/src/main/java/com/susu/domain/usecase/statistics/GetSusuStatisticsUseCase.kt
  feature/navigator/src/main/java/com/susu/feature/navigator/MainScreen.kt
  feature/statistics/src/main/java/com/susu/feature/statistics/StatisticsScreen.kt
  feature/statistics/src/main/java/com/susu/feature/statistics/component/RecentSpentGraph.kt
  feature/statistics/src/main/java/com/susu/feature/statistics/component/StatisticsItem.kt
  feature/statistics/src/main/java/com/susu/feature/statistics/content/my/MyStatisticsContent.kt
  feature/statistics/src/main/java/com/susu/feature/statistics/content/my/MyStatisticsContract.kt
  feature/statistics/src/main/java/com/susu/feature/statistics/content/my/MyStatisticsViewModel.kt
  feature/statistics/src/main/java/com/susu/feature/statistics/content/susu/SusuStatisticsContent.kt
  feature/statistics/src/main/java/com/susu/feature/statistics/content/susu/SusuStatisticsContract.kt
  feature/statistics/src/main/java/com/susu/feature/statistics/content/susu/SusuStatisticsOptionSlot.kt
  feature/statistics/src/main/java/com/susu/feature/statistics/content/susu/SusuStatisticsViewModel.kt
  feature/statistics/src/main/java/com/susu/feature/statistics/navigation/StatisticsNavigation.kt
  feature/statistics/src/main/res/drawable/ic_statistics_arrow_down.xml
  feature/statistics/src/main/res/values/strings.xml
Labels: feature

#122 Refactor/susu-dialog SusuDialog를 Dialog 컴포넌트를 활용하여 수정
  core/designsystem/src/main/java/com/susu/core/designsystem/component/dialog/SusuCheckedDialog.kt
  core/designsystem/src/main/java/com/susu/core/designsystem/component/dialog/SusuDialog.kt
  core/ui/src/main/java/com/susu/core/ui/DialogToken.kt
  feature/navigator/src/main/java/com/susu/feature/navigator/MainScreen.kt
Labels: refactor

#126 Feature/mz 138 sent search
  data/src/main/java/com/susu/data/data/di/RepositoryModule.kt
  data/src/main/java/com/susu/data/data/repository/EnvelopeRecentSearchRepositoryImpl.kt
  data/src/main/java/com/susu/data/local/RoomDataBase.kt
  data/src/main/java/com/susu/data/local/dao/EnvelopeRecentSearchDao.kt
  data/src/main/java/com/susu/data/local/di/DaoModule.kt
  domain/src/main/java/com/susu/domain/repository/EnvelopeRecentSearchRepository.kt
  domain/src/main/java/com/susu/domain/usecase/envelope/SearchSentEnvelopeListUseCase.kt
  domain/src/main/java/com/susu/domain/usecase/enveloperecentsearch/DeleteEnvelopeRecentSearchUseCase.kt
  domain/src/main/java/com/susu/domain/usecase/enveloperecentsearch/GetEnvelopeRecentSearchListUseCase.kt
  domain/src/main/java/com/susu/domain/usecase/enveloperecentsearch/UpsertEnvelopeRecentSearchUseCase.kt
  feature/navigator/src/main/java/com/susu/feature/navigator/MainNavigator.kt
  feature/navigator/src/main/java/com/susu/feature/navigator/MainScreen.kt
  feature/sent/src/main/java/com/susu/feature/envelopesearch/SentEnvelopeSearchContract.kt
  feature/sent/src/main/java/com/susu/feature/envelopesearch/SentEnvelopeSearchScreen.kt
  feature/sent/src/main/java/com/susu/feature/envelopesearch/SentEnvelopeSearchViewModel.kt
  feature/sent/src/main/java/com/susu/feature/sent/SentScreen.kt
  feature/sent/src/main/java/com/susu/feature/sent/component/SentCard.kt
  feature/sent/src/main/java/com/susu/feature/sent/navigation/SentNavigation.kt
  feature/sent/src/main/res/drawable/ic_envelope.xml
  feature/sent/src/main/res/drawable/img_envelope.xml
  feature/sent/src/main/res/values/strings.xml
Labels: feature

#127 Fix/sent change update 보내요 추가/삭제에 따른 화면 변화
  core/designsystem/src/main/java/com/susu/core/designsystem/component/text/SelectDateRow.kt
  core/designsystem/src/main/res/values/strings.xml
  core/ui/src/main/java/com/susu/core/ui/util/AnnotatedText.kt
  feature/navigator/src/main/java/com/susu/feature/navigator/MainScreen.kt
  feature/received/src/main/java/com/susu/feature/received/envelopeadd/content/date/DateContent.kt
  feature/received/src/main/java/com/susu/feature/received/ledgeradd/content/date/DateContent.kt
  feature/received/src/main/java/com/susu/feature/received/ledgeradd/content/date/component/SelectDateRow.kt
  feature/sent/src/main/java/com/susu/feature/envelope/SentEnvelopeContract.kt
  feature/sent/src/main/java/com/susu/feature/envelope/SentEnvelopeScreen.kt
  feature/sent/src/main/java/com/susu/feature/envelope/SentEnvelopeViewModel.kt
  feature/sent/src/main/java/com/susu/feature/envelopeadd/EnvelopeAddContract.kt
  feature/sent/src/main/java/com/susu/feature/envelopeadd/EnvelopeAddViewModel.kt
  feature/sent/src/main/java/com/susu/feature/envelopeadd/SentEnvelopeAddScreen.kt
  feature/sent/src/main/java/com/susu/feature/envelopeadd/content/date/DateContent.kt
  feature/sent/src/main/java/com/susu/feature/sent/SentContract.kt
  feature/sent/src/main/java/com/susu/feature/sent/SentScreen.kt
  feature/sent/src/main/java/com/susu/feature/sent/SentViewModel.kt
  feature/sent/src/main/java/com/susu/feature/sent/navigation/SentNavigation.kt
Labels: feature, fix

#128 Fix/statistic-api-change 통계 api url 변경
  data/src/main/java/com/susu/data/remote/api/StatisticsService.kt
  data/src/main/java/com/susu/data/remote/model/response/StatisticsResponse.kt
  feature/statistics/src/main/java/com/susu/feature/statistics/content/susu/SusuStatisticsContent.kt
  feature/statistics/src/main/java/com/susu/feature/statistics/content/susu/SusuStatisticsContract.kt
  feature/statistics/src/main/res/values/strings.xml
Labels: fix

#130 Feature/mz 143 sent filter
  core/model/src/main/java/com/susu/core/model/EnvelopeSearch.kt
  core/model/src/main/java/com/susu/core/model/FriendStatistics.kt
  data/src/main/java/com/susu/data/data/repository/EnvelopesRepositoryImpl.kt
  data/src/main/java/com/susu/data/remote/api/EnvelopesService.kt
  domain/src/main/java/com/susu/domain/repository/EnvelopesRepository.kt
  domain/src/main/java/com/susu/domain/usecase/envelope/GetEnvelopesListUseCase.kt
  feature/navigator/src/main/java/com/susu/feature/navigator/MainScreen.kt
  feature/sent/src/main/java/com/susu/feature/envelopefilter/EnvelopeFilterContract.kt
  feature/sent/src/main/java/com/susu/feature/envelopefilter/EnvelopeFilterScreen.kt
  feature/sent/src/main/java/com/susu/feature/envelopefilter/EnvelopeFilterViewModel.kt
  feature/sent/src/main/java/com/susu/feature/sent/SentContract.kt
  feature/sent/src/main/java/com/susu/feature/sent/SentScreen.kt
  feature/sent/src/main/java/com/susu/feature/sent/SentViewModel.kt
  feature/sent/src/main/java/com/susu/feature/sent/component/SentCard.kt
  feature/sent/src/main/java/com/susu/feature/sent/navigation/SentNavigation.kt
  feature/sent/src/main/res/values/strings.xml
Labels: feature, 🚨 ASAP

#134 Qa/12 13 ledger card radius cursor layer
  core/designsystem/src/main/java/com/susu/core/designsystem/component/textfieldbutton/SusuTextFieldButton.kt
  feature/received/src/main/java/com/susu/feature/received/received/component/LedgerAddCard.kt
  feature/received/src/main/java/com/susu/feature/received/received/component/LedgerCard.kt
Labels: QA

#135 QA-6/보내요 봉투 수정사항이 받아요 화면에 반영이 되지 않는 현상
  feature/navigator/src/main/java/com/susu/feature/navigator/MainScreen.kt
  feature/sent/src/main/java/com/susu/feature/envelope/SentEnvelopeScreen.kt
  feature/sent/src/main/java/com/susu/feature/envelopedetail/SentEnvelopeDetailScreen.kt
  feature/sent/src/main/java/com/susu/feature/envelopeedit/SentEnvelopeEditContract.kt
  feature/sent/src/main/java/com/susu/feature/envelopeedit/SentEnvelopeEditScreen.kt
  feature/sent/src/main/java/com/susu/feature/envelopeedit/SentEnvelopeEditViewModel.kt
  feature/sent/src/main/java/com/susu/feature/sent/SentContract.kt
  feature/sent/src/main/java/com/susu/feature/sent/SentScreen.kt
  feature/sent/src/main/java/com/susu/feature/sent/SentViewModel.kt
  feature/sent/src/main/java/com/susu/feature/sent/component/SentCard.kt
  feature/sent/src/main/java/com/susu/feature/sent/navigation/SentNavigation.kt
Labels: QA

#136 QA/14 보내요, 받아요 페이지 스크롤 시 정렬, 필터 동작
  feature/received/src/main/java/com/susu/feature/received/received/ReceivedScreen.kt
  feature/sent/src/main/java/com/susu/feature/sent/SentScreen.kt
Labels: QA

#137 Qa/28 날짜 입력 진입 시 바텀시트 바로 뜨지 않음
  feature/received/src/main/java/com/susu/feature/received/envelopeadd/ReceivedEnvelopeAddScreen.kt
  feature/received/src/main/java/com/susu/feature/received/envelopeadd/ReceivedEnvelopeAddViewModel.kt
  feature/received/src/main/java/com/susu/feature/received/envelopeadd/content/date/DateContent.kt
  feature/received/src/main/java/com/susu/feature/received/envelopeadd/content/date/DateViewModel.kt
  feature/received/src/main/java/com/susu/feature/received/ledgeradd/LedgerAddContract.kt
  feature/received/src/main/java/com/susu/feature/received/ledgeradd/LedgerAddScreen.kt
  feature/received/src/main/java/com/susu/feature/received/ledgeradd/LedgerAddViewModel.kt
  feature/received/src/main/java/com/susu/feature/received/ledgeradd/content/date/DateContract.kt
  feature/received/src/main/java/com/susu/feature/received/ledgeradd/content/date/DateViewModel.kt
  feature/sent/src/main/java/com/susu/feature/envelopeadd/content/date/DateContract.kt
Labels: QA

#138 Qa/34 로그아웃 후 다른 계정으로 로그인 시, 이전 계정의 데이터가 노출되는 현상
  data/src/main/java/com/susu/data/Constants.kt
  data/src/main/java/com/susu/data/data/repository/LoginRepositoryImpl.kt
  data/src/main/java/com/susu/data/data/repository/SignUpRepositoryImpl.kt
  data/src/main/java/com/susu/data/data/repository/UserRepositoryImpl.kt
  data/src/main/java/com/susu/data/remote/Constants.kt
  data/src/main/java/com/susu/data/remote/di/NetworkModule.kt
  domain/src/main/java/com/susu/domain/repository/SignUpRepository.kt
  domain/src/main/java/com/susu/domain/usecase/loginsignup/CheckShowOnboardVoteUseCase.kt
  feature/loginsignup/src/main/java/com/susu/feature/loginsignup/social/KakaoLoginHelper.kt
  feature/mypage/src/main/java/com/susu/feature/mypage/main/MyPageDefaultScreen.kt
  feature/mypage/src/main/java/com/susu/feature/mypage/navigation/MyPageNavigation.kt
  feature/navigator/src/main/java/com/susu/feature/navigator/MainActivity.kt
  feature/navigator/src/main/java/com/susu/feature/navigator/MainScreen.kt
  feature/navigator/src/main/java/com/susu/feature/navigator/MainViewModel.kt
Labels: fix

#139 Qa/9-10-43 회원가입(약관, 출생년도), 마이페이지(출생년도) 관련 수정
  core/designsystem/src/main/java/com/susu/core/designsystem/component/bottomsheet/datepicker/SusuDatePickerBottomSheet.kt
  core/ui/src/main/java/com/susu/core/ui/Consts.kt
  feature/loginsignup/src/main/java/com/susu/feature/loginsignup/signup/SignUpScreen.kt
  feature/loginsignup/src/main/java/com/susu/feature/loginsignup/signup/content/TermsContent.kt
  feature/mypage/src/main/java/com/susu/feature/mypage/info/MyPageInfoScreen.kt
Labels: QA

#140 Qa/20 29 31 39 통계 관련 수정사항
  data/src/main/java/com/susu/data/data/repository/StatisticsRepositoryImpl.kt
  feature/statistics/src/main/java/com/susu/feature/statistics/component/RecentSpentGraph.kt
  feature/statistics/src/main/java/com/susu/feature/statistics/content/my/MyStatisticsContent.kt
  feature/statistics/src/main/java/com/susu/feature/statistics/content/susu/SusuStatisticsContent.kt
  feature/statistics/src/main/res/values/strings.xml
Labels: QA

#141 Qa/22 당겨서 새로 고침
  feature/community/src/main/java/com/susu/feature/community/community/CommunityScreen.kt
  feature/community/src/main/java/com/susu/feature/community/community/CommunityViewModel.kt
  feature/community/src/main/java/com/susu/feature/community/votedetail/VoteDetailScreen.kt
  feature/community/src/main/java/com/susu/feature/community/votedetail/VoteDetailViewModel.kt
  feature/received/src/main/java/com/susu/feature/received/ledgerdetail/LedgerDetailScreen.kt
  feature/received/src/main/java/com/susu/feature/received/ledgerdetail/LedgerDetailViewModel.kt
  feature/received/src/main/java/com/susu/feature/received/received/ReceivedScreen.kt
  feature/received/src/main/java/com/susu/feature/received/received/ReceivedViewModel.kt
  feature/sent/src/main/java/com/susu/feature/envelope/SentEnvelopeScreen.kt
  feature/sent/src/main/java/com/susu/feature/envelope/SentEnvelopeViewModel.kt
  feature/sent/src/main/java/com/susu/feature/sent/SentScreen.kt
  feature/sent/src/main/java/com/susu/feature/sent/SentViewModel.kt
  feature/statistics/src/main/java/com/susu/feature/statistics/content/my/MyStatisticsContent.kt
  feature/statistics/src/main/java/com/susu/feature/statistics/content/my/MyStatisticsViewModel.kt
  feature/statistics/src/main/java/com/susu/feature/statistics/content/susu/SusuStatisticsContent.kt
  feature/statistics/src/main/java/com/susu/feature/statistics/content/susu/SusuStatisticsViewModel.kt
Labels: QA

#144 Qa/23 투표 유효성 검증 변경
  feature/community/src/main/java/com/susu/feature/community/Const.kt
  feature/community/src/main/java/com/susu/feature/community/navigation/CommunityNavigation.kt
  feature/community/src/main/java/com/susu/feature/community/voteadd/VoteAddContract.kt
  feature/community/src/main/java/com/susu/feature/community/voteadd/VoteAddScreen.kt
  feature/community/src/main/java/com/susu/feature/community/voteadd/VoteAddViewModel.kt
  feature/community/src/main/java/com/susu/feature/community/voteedit/VoteEditContract.kt
  feature/community/src/main/java/com/susu/feature/community/voteedit/VoteEditScreen.kt
  feature/community/src/main/java/com/susu/feature/community/voteedit/VoteEditViewModel.kt
  feature/community/src/main/res/values/strings.xml
  feature/navigator/src/main/java/com/susu/feature/navigator/MainNavigator.kt
  feature/received/src/main/java/com/susu/feature/received/ledgeredit/LedgerEditScreen.kt
Labels: QA

#145 Qa/26 51 브라우저 미설치 강제종료, 웹뷰 상단에 앱바 추가
  feature/mypage/src/main/java/com/susu/feature/mypage/MyPagePrivacyPolicyScreen.kt
  feature/mypage/src/main/java/com/susu/feature/mypage/main/MyPageDefaultScreen.kt
  feature/mypage/src/main/java/com/susu/feature/mypage/navigation/MyPageNavigation.kt
  feature/mypage/src/main/java/com/susu/feature/mypage/social/MyPageSocialScreen.kt
  feature/mypage/src/main/res/values/strings.xml
Labels: QA

#147 docs: update README
  README.md
Labels: documentation

#146 Qa/48 카카오톡, 브라우저 모두 미 설치 케이스 대응
  feature/loginsignup/src/main/java/com/susu/feature/loginsignup/login/LoginContract.kt
  feature/loginsignup/src/main/java/com/susu/feature/loginsignup/login/LoginScreen.kt
  feature/loginsignup/src/main/java/com/susu/feature/loginsignup/login/LoginViewModel.kt
  feature/loginsignup/src/main/java/com/susu/feature/loginsignup/navigation/LoginSignupNavigation.kt
  feature/loginsignup/src/main/java/com/susu/feature/loginsignup/signup/SignUpContract.kt
  feature/loginsignup/src/main/java/com/susu/feature/loginsignup/signup/SignUpScreen.kt
  feature/loginsignup/src/main/java/com/susu/feature/loginsignup/signup/SignUpViewModel.kt
  feature/loginsignup/src/main/res/values/strings.xml
  feature/navigator/src/main/java/com/susu/feature/navigator/MainScreen.kt
Labels: QA

#148 Qa/15 21 sent card
  feature/sent/src/main/java/com/susu/feature/envelope/SentEnvelopeScreen.kt
  feature/sent/src/main/java/com/susu/feature/sent/component/SentCard.kt
  feature/sent/src/main/res/values/strings.xml
Labels: QA

#150 Qa/47 sent card focus
  feature/received/src/main/java/com/susu/feature/received/envelopeadd/ReceivedEnvelopeAddViewModel.kt
  feature/received/src/main/java/com/susu/feature/received/ledgeradd/content/date/DateContent.kt
  feature/received/src/main/java/com/susu/feature/received/ledgeradd/content/date/DateContract.kt
  feature/sent/src/main/java/com/susu/feature/sent/SentContract.kt
  feature/sent/src/main/java/com/susu/feature/sent/SentScreen.kt
  feature/sent/src/main/java/com/susu/feature/sent/SentViewModel.kt
Labels: QA

#154 Qa/72 인물 봉투 상세에서 봉투 생성 플로우 추가
  feature/navigator/src/main/java/com/susu/feature/navigator/MainNavigator.kt
  feature/sent/src/main/java/com/susu/feature/envelope/SentEnvelopeContract.kt
  feature/sent/src/main/java/com/susu/feature/envelope/SentEnvelopeScreen.kt
  feature/sent/src/main/java/com/susu/feature/envelope/SentEnvelopeViewModel.kt
  feature/sent/src/main/java/com/susu/feature/envelopeadd/EnvelopeAddContract.kt
  feature/sent/src/main/java/com/susu/feature/envelopeadd/EnvelopeAddViewModel.kt
  feature/sent/src/main/java/com/susu/feature/envelopeadd/SentEnvelopeAddScreen.kt
  feature/sent/src/main/java/com/susu/feature/envelopeadd/content/more/MoreContent.kt
  feature/sent/src/main/java/com/susu/feature/sent/navigation/SentNavigation.kt
Labels: QA

#155 Qa/75 78 LoginScreen 실제 투표 데이터로 교체, 로고 위치 조정
  core/model/src/main/java/com/susu/core/model/OnboardVote.kt
  data/src/main/java/com/susu/data/data/di/RepositoryModule.kt
  data/src/main/java/com/susu/data/data/repository/OnboardRepositoryImpl.kt
  data/src/main/java/com/susu/data/remote/api/OnboardService.kt
  data/src/main/java/com/susu/data/remote/di/ApiServiceModule.kt
  data/src/main/java/com/susu/data/remote/model/response/OnboardVoteResponse.kt
  domain/src/main/java/com/susu/domain/repository/OnboardRepository.kt
  domain/src/main/java/com/susu/domain/usecase/loginsignup/GetOnboardVoteUseCase.kt
  feature/loginsignup/src/main/java/com/susu/feature/loginsignup/login/LoginArchGraph.kt
  feature/loginsignup/src/main/java/com/susu/feature/loginsignup/login/LoginContract.kt
  feature/loginsignup/src/main/java/com/susu/feature/loginsignup/login/LoginScreen.kt
  feature/loginsignup/src/main/java/com/susu/feature/loginsignup/login/LoginViewModel.kt
  feature/loginsignup/src/main/res/values/strings.xml
Labels: QA

#161 Qa/80 출생년도 '미선택' 선택 시, 강제종료
  core/model/src/main/java/com/susu/core/model/SignUpUser.kt
  data/src/main/java/com/susu/data/data/repository/UserRepositoryImpl.kt
  data/src/main/java/com/susu/data/remote/model/request/UserRequest.kt
  domain/src/main/java/com/susu/domain/repository/UserRepository.kt
  domain/src/main/java/com/susu/domain/usecase/mypage/PatchUserUseCase.kt
  feature/loginsignup/src/main/java/com/susu/feature/loginsignup/signup/SignUpViewModel.kt
  feature/loginsignup/src/main/java/com/susu/feature/loginsignup/signup/content/AdditionalContent.kt
  feature/mypage/src/main/java/com/susu/feature/mypage/info/MyPageInfoViewModel.kt
Labels: 🚨 ASAP, QA

#162 Qa/19 101 107 112 봉투/장부 편집 관련 이슈
  core/designsystem/src/main/java/com/susu/core/designsystem/component/bottomsheet/datepicker/SusuDatePickerBottomSheet.kt
  core/ui/src/main/java/com/susu/core/ui/Consts.kt
  feature/received/src/main/java/com/susu/feature/received/envelopeadd/content/memo/MemoViewModel.kt
  feature/received/src/main/java/com/susu/feature/received/envelopeadd/content/money/MoneyViewModel.kt
  feature/received/src/main/java/com/susu/feature/received/envelopeadd/content/name/NameViewModel.kt
  feature/received/src/main/java/com/susu/feature/received/envelopeadd/content/phone/PhoneViewModel.kt
  feature/received/src/main/java/com/susu/feature/received/envelopeadd/content/present/PresentViewModel.kt
  feature/received/src/main/java/com/susu/feature/received/envelopeadd/content/relationship/RelationShipViewModel.kt
  feature/received/src/main/java/com/susu/feature/received/envelopeedit/ReceivedEnvelopeEditViewModel.kt
  feature/received/src/main/java/com/susu/feature/received/ledgeradd/content/category/CategoryViewModel.kt
  feature/received/src/main/java/com/susu/feature/received/ledgeradd/content/name/NameViewModel.kt
  feature/received/src/main/java/com/susu/feature/received/ledgeredit/LedgerEditViewModel.kt
  feature/sent/src/main/java/com/susu/feature/envelopeadd/content/category/CategoryViewModel.kt
  feature/sent/src/main/java/com/susu/feature/envelopeadd/content/memo/MemoViewModel.kt
  feature/sent/src/main/java/com/susu/feature/envelopeadd/content/money/MoneyViewModel.kt
  feature/sent/src/main/java/com/susu/feature/envelopeadd/content/name/NameViewModel.kt
  feature/sent/src/main/java/com/susu/feature/envelopeadd/content/phone/PhoneViewModel.kt
  feature/sent/src/main/java/com/susu/feature/envelopeadd/content/present/PresentViewModel.kt
  feature/sent/src/main/java/com/susu/feature/envelopeadd/content/relationship/RelationshipViewModel.kt
  feature/sent/src/main/java/com/susu/feature/envelopeedit/SentEnvelopeEditContract.kt
  feature/sent/src/main/java/com/susu/feature/envelopeedit/SentEnvelopeEditScreen.kt
  feature/sent/src/main/java/com/susu/feature/envelopeedit/SentEnvelopeEditViewModel.kt
Labels: QA
