Repository YAPP-Github/oksusu-susu-android, pull requests merged in 2024-01, with the labels that each got.

#24 Feature/mz 155 textfield button
  core/designsystem/src/main/java/com/susu/core/designsystem/component/button/BasicButton.kt
  core/designsystem/src/main/java/com/susu/core/designsystem/component/button/SusuFilledButton.kt
  core/designsystem/src/main/java/com/susu/core/designsystem/component/button/SusuGhostButton.kt
  core/designsystem/src/main/java/com/susu/core/designsystem/component/button/SusuLinedButton.kt
  core/designsystem/src/main/java/com/susu/core/designsystem/component/textfieldbutton/SusuTextFieldButton.kt
  core/designsystem/src/main/java/com/susu/core/designsystem/component/textfieldbutton/TextFieldButtonColor.kt
  core/designsystem/src/main/java/com/susu/core/designsystem/component/textfieldbutton/style/InnerButtonStyle.kt
  core/designsystem/src/main/java/com/susu/core/designsystem/component/textfieldbutton/style/TextFieldButtonStyle.kt
  core/designsystem/src/main/java/com/susu/core/designsystem/theme/Spacing.kt
  core/designsystem/src/main/java/com/susu/core/designsystem/theme/Theme.kt
  core/designsystem/src/main/res/drawable/ic_clear.xml
  core/designsystem/src/main/res/drawable/ic_close.xml
  core/designsystem/src/main/res/values/strings.xml
  core/ui/src/main/java/com/susu/core/ui/extension/Modifier.kt
Labels: feature

#25 Feature/mz 157 appbar
  core/designsystem/src/main/java/com/susu/core/designsystem/component/appbar/BasicAppBar.kt
  core/designsystem/src/main/java/com/susu/core/designsystem/component/appbar/ProgressBarStyle.kt
  core/designsystem/src/main/java/com/susu/core/designsystem/component/appbar/SusuDefaultAppBar.kt
  core/designsystem/src/main/java/com/susu/core/designsystem/component/appbar/SusuProgressAppBar.kt
  feature/navigator/src/main/java/com/susu/feature/navigator/MainNavigationTab.kt
  feature/navigator/src/main/res/drawable/ic_community_filled.xml
  feature/navigator/src/main/res/drawable/ic_community_outlined.xml
  feature/navigator/src/main/res/drawable/ic_my_page_filled.xml
  feature/navigator/src/main/res/drawable/ic_my_page_outlined.xml
  feature/navigator/src/main/res/drawable/ic_received_filled.xml
  feature/navigator/src/main/res/drawable/ic_received_outlined.xml
  feature/navigator/src/main/res/drawable/ic_sent_filled.xml
  feature/navigator/src/main/res/drawable/ic_sent_outlined.xml
  feature/navigator/src/main/res/drawable/ic_statistics_filled.xml
  feature/navigator/src/main/res/drawable/ic_statistics_outlined.xml
Labels: feature

#22 Feature/mz 156 badge
  core/designsystem/src/main/java/com/susu/core/designsystem/component/badge/BadgeColor.kt
  core/designsystem/src/main/java/com/susu/core/designsystem/component/badge/BadgePadding.kt
  core/designsystem/src/main/java/com/susu/core/designsystem/component/badge/SusuBadge.kt
Labels: feature

#34 Feature/retrofit2
  core/model/src/main/java/com/susu/core/model/MyClass.kt
  core/model/src/main/java/com/susu/core/model/exception/CommonExceptions.kt
  core/model/src/main/java/com/susu/core/model/exception/SusuExceptions.kt
  data/src/main/java/com/susu/data/Json.kt
  data/src/main/java/com/susu/data/JsonSingleton.kt
  data/src/main/java/com/susu/data/Sample.kt
  data/src/main/java/com/susu/data/di/ApiServiceModule.kt
  data/src/main/java/com/susu/data/di/NetworkModule.kt
  data/src/main/java/com/susu/data/network/service/SignUpService.kt
  data/src/main/java/com/susu/data/network/service/UserService.kt
  data/src/main/java/com/susu/data/repository/LoginRepositoryImpl.kt
  data/src/main/java/com/susu/data/repository/SignUpRepositoryImpl.kt
  data/src/main/java/com/susu/data/retrofit/ApiResult.kt
  data/src/main/java/com/susu/data/retrofit/ApiResultCallAdapter.kt
  data/src/main/java/com/susu/data/retrofit/ResultCallAdapterFactory.kt
  data/src/main/java/com/susu/data/retrofit/SusuErrorResponse.kt
Labels: feature

#32 Feature/mz 158 ledger list align UI
  core/designsystem/build.gradle.kts
  core/designsystem/src/main/java/com/susu/core/designsystem/component/bottomsheet/SusuBottomSheet.kt
  core/designsystem/src/main/java/com/susu/core/designsystem/component/bottomsheet/SusuSelectionBottomSheet.kt
  core/designsystem/src/main/java/com/susu/core/designsystem/component/button/BasicButton.kt
  core/designsystem/src/main/java/com/susu/core/designsystem/component/button/SusuFilledButton.kt
  core/designsystem/src/main/java/com/susu/core/designsystem/component/button/SusuFloatingButton.kt
  core/designsystem/src/main/java/com/susu/core/designsystem/component/button/SusuGhostButton.kt
  core/designsystem/src/main/java/com/susu/core/designsystem/component/button/SusuLinedButton.kt
  core/designsystem/src/main/java/com/susu/core/designsystem/shadow/SusuShadow.kt
  core/designsystem/src/main/java/com/susu/core/designsystem/theme/Typography.kt
  core/designsystem/src/main/res/drawable/ic_floating_button_add.xml
  core/ui/src/main/java/com/susu/core/ui/Consts.kt
  core/ui/src/main/res/drawable/ic_align.xml
  core/ui/src/main/res/drawable/ic_appbar_notification.xml
  core/ui/src/main/res/drawable/ic_appbar_search.xml
  core/ui/src/main/res/drawable/ic_filter.xml
  core/ui/src/main/res/drawable/ic_logo.xml
  core/ui/src/main/res/values/strings.xml
  feature/received/src/main/java/com/susu/feature/received/ReceivedScreen.kt
  feature/received/src/main/java/com/susu/feature/received/component/LedgerAddCard.kt
  feature/received/src/main/java/com/susu/feature/received/component/LedgerCard.kt
  feature/received/src/main/java/com/susu/feature/received/navigation/ReceivedNavigation.kt
  feature/received/src/main/res/drawable/ic_ledger_add.xml
  feature/received/src/main/res/values/strings.xml
Labels: feature

#30 Feature/mz 159 Textfield Component
  core/designsystem/src/main/java/com/susu/core/designsystem/component/textfield/PriceVisualTransformation.kt
  core/designsystem/src/main/java/com/susu/core/designsystem/component/textfield/SusuTextField.kt
  core/designsystem/src/main/java/com/susu/core/designsystem/component/textfield/SusuUnderlineTextField.kt
  core/designsystem/src/main/java/com/susu/core/designsystem/component/textfieldbutton/SusuTextFieldButton.kt
  core/designsystem/src/main/java/com/susu/core/designsystem/component/util/ClearIconButton.kt
  core/designsystem/src/main/res/values/strings.xml
Labels: feature

#36 Hotfix/refresh-token 토큰 만료시 갱신하지 못하는 현상
  data/src/main/java/com/susu/data/model/request/RefreshTokenRequest.kt
  data/src/main/java/com/susu/data/network/TokenAuthenticator.kt
  data/src/main/java/com/susu/data/network/TokenInterceptor.kt
Labels: fix

#39 Feature/mz 117 sent envelopes list
  core/designsystem/src/main/java/com/susu/core/designsystem/component/appbar/ProgressBarStyle.kt
  core/designsystem/src/main/java/com/susu/core/designsystem/component/badge/BadgePadding.kt
  feature/sent/src/main/java/com/susu/feature/sent/EnvelopeCard.kt
  feature/sent/src/main/java/com/susu/feature/sent/EnvelopeHistoryCard.kt
  feature/sent/src/main/java/com/susu/feature/sent/SentScreen.kt
  feature/sent/src/main/res/drawable/ic_arrow_down.xml
  feature/sent/src/main/res/drawable/ic_envelope.xml
  feature/sent/src/main/res/drawable/ic_filter.xml
  feature/sent/src/main/res/drawable/ic_notification.xml
  feature/sent/src/main/res/drawable/ic_round_arrow_received.xml
  feature/sent/src/main/res/drawable/ic_round_arrow_sent.xml
  feature/sent/src/main/res/drawable/ic_search.xml
  feature/sent/src/main/res/drawable/ic_sort.xml
  feature/sent/src/main/res/drawable/ic_susu_app.xml
  feature/sent/src/main/res/values/strings.xml
Labels: feature

#42 Feature/mz 164 ledger detail UI
  core/designsystem/src/main/java/com/susu/core/designsystem/component/appbar/icon/DeleteText.kt
  core/designsystem/src/main/java/com/susu/core/designsystem/component/appbar/icon/EditText.kt
  core/designsystem/src/main/java/com/susu/core/designsystem/component/bottomsheet/SusuBottomSheet.kt
  core/ui/src/main/java/com/susu/core/ui/extension/Int.kt
  core/ui/src/main/res/drawable/ic_arrow_right.xml
  core/ui/src/main/res/values/strings.xml
  feature/navigator/src/main/java/com/susu/feature/navigator/MainNavigator.kt
  feature/navigator/src/main/java/com/susu/feature/navigator/MainScreen.kt
  feature/received/src/main/java/com/susu/feature/received/ledgerdetail/LedgerDetailContract.kt
  feature/received/src/main/java/com/susu/feature/received/ledgerdetail/LedgerDetailScreen.kt
  feature/received/src/main/java/com/susu/feature/received/ledgerdetail/LedgerDetailViewModel.kt
  feature/received/src/main/java/com/susu/feature/received/ledgerdetail/component/LedgerDetailEnvelopeContainer.kt
  feature/received/src/main/java/com/susu/feature/received/ledgerdetail/component/LedgerDetailOverviewColumn.kt
  feature/received/src/main/java/com/susu/feature/received/navigation/ReceivedNavigation.kt
  feature/received/src/main/java/com/susu/feature/received/received/ReceivedScreen.kt
  feature/received/src/main/java/com/susu/feature/received/received/component/LedgerCard.kt
  feature/received/src/main/res/values/strings.xml
Labels: feature

#44 Feature/refactor init route and create snackbar
  core/designsystem/src/main/java/com/susu/core/designsystem/component/screen/LoadingScreen.kt
  core/designsystem/src/main/java/com/susu/core/designsystem/component/snackbar/SusuSnackbar.kt
  core/designsystem/src/main/java/com/susu/core/designsystem/component/util/LoadingScreen.kt
  core/ui/src/main/java/com/susu/core/ui/SnackbarToken.kt
  feature/loginsignup/src/main/java/com/susu/feature/loginsignup/login/LoginScreen.kt
  feature/loginsignup/src/main/java/com/susu/feature/loginsignup/social/KakaoLoginHelper.kt
  feature/navigator/src/main/java/com/susu/feature/navigator/MainActivity.kt
  feature/navigator/src/main/java/com/susu/feature/navigator/MainContract.kt
  feature/navigator/src/main/java/com/susu/feature/navigator/MainNavigator.kt
  feature/navigator/src/main/java/com/susu/feature/navigator/MainScreen.kt
  feature/navigator/src/main/java/com/susu/feature/navigator/MainViewModel.kt
  feature/navigator/src/main/java/com/susu/feature/navigator/initialization/InitialRoute.kt
  feature/navigator/src/main/java/com/susu/feature/navigator/initialization/MainContract.kt
  feature/navigator/src/main/java/com/susu/feature/navigator/initialization/MainViewModel.kt
Labels: feature

#47 Feature/mz 172 장부 편집 화면 UI, status bar 색상
  core/designsystem/src/main/java/com/susu/core/designsystem/component/button/AddConditionButton.kt
  core/designsystem/src/main/java/com/susu/core/designsystem/component/textfieldbutton/SusuTextFieldButton.kt
  core/designsystem/src/main/res/values/strings.xml
  core/ui/src/main/java/com/susu/core/ui/util/AnnotatedText.kt
  core/ui/src/main/res/drawable/ic_add.xml
  core/ui/src/main/res/values/strings.xml
  feature/navigator/build.gradle.kts
  feature/navigator/src/main/java/com/susu/feature/navigator/MainNavigator.kt
  feature/navigator/src/main/java/com/susu/feature/navigator/MainScreen.kt
  feature/received/src/main/java/com/susu/feature/received/ledgerdetail/LedgerDetailScreen.kt
  feature/received/src/main/java/com/susu/feature/received/ledgeredit/LedgerEditScreen.kt
  feature/received/src/main/java/com/susu/feature/received/ledgeredit/component/LedgerEditContainer.kt
  feature/received/src/main/java/com/susu/feature/received/navigation/ReceivedNavigation.kt
  feature/received/src/main/java/com/susu/feature/received/received/ReceivedScreen.kt
  feature/received/src/main/res/values/strings.xml
  gradle/libs.versions.toml
Labels: feature

#48 Feature/mz 173 날짜 선택 컴포넌트
  core/designsystem/src/main/java/com/susu/core/designsystem/component/bottomsheet/datepicker/InfiniteColumn.kt
  core/designsystem/src/main/java/com/susu/core/designsystem/component/bottomsheet/datepicker/SusuDatePickerBottomSheet.kt
  core/designsystem/src/main/res/values/strings.xml
Labels: feature

#52 Feature/mz 111 약관 동의, 회원가입 UI
  core/designsystem/src/main/java/com/susu/core/designsystem/component/appbar/SusuProgressAppBar.kt
  core/model/src/main/java/com/susu/core/model/Term.kt
  core/model/src/main/java/com/susu/core/model/TermDetail.kt
  core/model/src/main/java/com/susu/core/model/User.kt
  core/ui/src/main/java/com/susu/core/ui/Consts.kt
  core/ui/src/main/res/values/strings.xml
  data/src/main/java/com/susu/data/data/di/RepositoryModule.kt
  data/src/main/java/com/susu/data/data/repository/TermRepositoryImpl.kt
  data/src/main/java/com/susu/data/remote/api/TermService.kt
  data/src/main/java/com/susu/data/remote/di/ApiServiceModule.kt
  data/src/main/java/com/susu/data/remote/model/request/UserRequest.kt
  data/src/main/java/com/susu/data/remote/model/response/TermResponse.kt
  domain/src/main/java/com/susu/domain/repository/TermRepository.kt
  domain/src/main/java/com/susu/domain/usecase/loginsignup/GetTermDetailUseCase.kt
  domain/src/main/java/com/susu/domain/usecase/loginsignup/GetTermsUseCase.kt
  feature/loginsignup/src/main/java/com/susu/feature/loginsignup/navigation/LoginSignupNavigation.kt
  feature/loginsignup/src/main/java/com/susu/feature/loginsignup/signup/SignUpContract.kt
  feature/loginsignup/src/main/java/com/susu/feature/loginsignup/signup/SignUpScreen.kt
  feature/loginsignup/src/main/java/com/susu/feature/loginsignup/signup/SignUpViewModel.kt
  feature/loginsignup/src/main/java/com/susu/feature/loginsignup/signup/TermContract.kt
  feature/loginsignup/src/main/java/com/susu/feature/loginsignup/signup/TermViewModel.kt
  feature/loginsignup/src/main/java/com/susu/feature/loginsignup/signup/content/AdditionalContent.kt
  feature/loginsignup/src/main/java/com/susu/feature/loginsignup/signup/content/NameContent.kt
  feature/loginsignup/src/main/java/com/susu/feature/loginsignup/signup/content/TermsContent.kt
  feature/loginsignup/src/main/res/values/strings.xml
  feature/navigator/src/main/java/com/susu/feature/navigator/MainNavigator.kt
  feature/navigator/src/main/java/com/susu/feature/navigator/MainScreen.kt
Labels: feature

#51 Feature/mz 174 add ledger UI textfield button focus state
  core/designsystem/src/main/java/com/susu/core/designsystem/component/textfieldbutton/SusuTextFieldButton.kt
  core/designsystem/src/main/java/com/susu/core/designsystem/component/textfieldbutton/TextFieldButtonColor.kt
  core/ui/src/main/java/com/susu/core/ui/extension/AnimatedContentTransitionScope.kt
  core/ui/src/main/res/values/strings.xml
  feature/navigator/src/main/java/com/susu/feature/navigator/MainNavigator.kt
  feature/navigator/src/main/java/com/susu/feature/navigator/MainScreen.kt
  feature/received/src/main/java/com/susu/feature/received/ledgeradd/LedgerAddScreen.kt
  feature/received/src/main/java/com/susu/feature/received/ledgeradd/content/CategoryContent.kt
  feature/received/src/main/java/com/susu/feature/received/ledgeradd/content/DateContent.kt
  feature/received/src/main/java/com/susu/feature/received/ledgeradd/content/NameContent.kt
  feature/received/src/main/java/com/susu/feature/received/ledgeradd/content/component/SelectDateRow.kt
  feature/received/src/main/java/com/susu/feature/received/navigation/ReceivedNavigation.kt
  feature/received/src/main/java/com/susu/feature/received/received/ReceivedScreen.kt
  feature/received/src/main/res/values/strings.xml
Labels: feature

#54 Feature/mz 169 sent envelopes detail
  feature/navigator/src/main/java/com/susu/feature/navigator/MainNavigator.kt
  feature/navigator/src/main/java/com/susu/feature/navigator/MainScreen.kt
  feature/sent/src/main/java/com/susu/feature/envelope/SentEnvelopeContract.kt
  feature/sent/src/main/java/com/susu/feature/envelope/SentEnvelopeScreen.kt
  feature/sent/src/main/java/com/susu/feature/envelope/SentEnvelopeViewModel.kt
  feature/sent/src/main/java/com/susu/feature/envelope/component/EnvelopeHistoryItem.kt
  feature/sent/src/main/java/com/susu/feature/envelopedetail/SentEnvelopeDetailContract.kt
  feature/sent/src/main/java/com/susu/feature/envelopedetail/SentEnvelopeDetailScreen.kt
  feature/sent/src/main/java/com/susu/feature/envelopedetail/SentEnvelopeDetailViewModel.kt
  feature/sent/src/main/java/com/susu/feature/envelopedetail/component/DetailItem.kt
  feature/sent/src/main/java/com/susu/feature/sent/EnvelopeHistoryCard.kt
  feature/sent/src/main/java/com/susu/feature/sent/SentScreen.kt
  feature/sent/src/main/java/com/susu/feature/sent/component/SentCard.kt
  feature/sent/src/main/java/com/susu/feature/sent/component/SentHistoryCard.kt
  feature/sent/src/main/java/com/susu/feature/sent/component/SentHistoryItem.kt
  feature/sent/src/main/java/com/susu/feature/sent/navigation/SentNavigation.kt
  feature/sent/src/main/res/drawable/ic_round_arrow_received.xml
  feature/sent/src/main/res/drawable/ic_round_arrow_sent.xml
  feature/sent/src/main/res/values/strings.xml
Labels: feature

#58 Feature/mz 177 dialog component
  core/designsystem/src/main/java/com/susu/core/designsystem/component/dialog/SusuDialog.kt
  core/ui/src/main/java/com/susu/core/ui/DialogToken.kt
  feature/navigator/src/main/java/com/susu/feature/navigator/MainContract.kt
  feature/navigator/src/main/java/com/susu/feature/navigator/MainScreen.kt
  feature/navigator/src/main/java/com/susu/feature/navigator/MainViewModel.kt
Labels: feature

#62 Feature/mz 179 ledger search
  core/designsystem/src/main/java/com/susu/core/designsystem/component/searchbar/SusuSearchBar.kt
  core/model/src/main/java/com/susu/core/model/Category.kt
  core/model/src/main/java/com/susu/core/model/Ledger.kt
  core/ui/src/main/res/values/strings.xml
  data/src/main/java/com/susu/data/data/di/RepositoryModule.kt
  data/src/main/java/com/susu/data/data/repository/LedgerRepositoryImpl.kt
  data/src/main/java/com/susu/data/remote/api/LedgerService.kt
  data/src/main/java/com/susu/data/remote/di/ApiServiceModule.kt
  data/src/main/java/com/susu/data/remote/model/response/LedgerListResponse.kt
  domain/src/main/java/com/susu/domain/repository/LedgerRepository.kt
  domain/src/main/java/com/susu/domain/usecase/ledger/GetLedgerListUseCase.kt
  feature/received/src/main/java/com/susu/feature/received/navigation/ReceivedNavigation.kt
  feature/received/src/main/java/com/susu/feature/received/search/LedgerSearchContract.kt
  feature/received/src/main/java/com/susu/feature/received/search/LedgerSearchScreen.kt
  feature/received/src/main/java/com/susu/feature/received/search/LedgerSearchViewModel.kt
  feature/received/src/main/res/drawable/ic_ledger.xml
  feature/received/src/main/res/values/strings.xml
Labels: feature, 🚨 ASAP

#66 Feature/datepicker-limit SusuLimitDatePickerBottomSheet 컴포넌트 추가
  core/designsystem/src/main/java/com/susu/core/designsystem/component/bottomsheet/datepicker/SusuDatePickerBottomSheet.kt
Labels: feature

#67 Feature/mz 180 ledger list edit delete, error handling, category config
  build-logic/convention/src/main/java/FeatureComposeConventionPlugin.kt
  core/designsystem/src/main/java/com/susu/core/designsystem/component/bottomsheet/datepicker/SusuDatePickerBottomSheet.kt
  core/designsystem/src/main/java/com/susu/core/designsystem/component/textfieldbutton/SusuTextFieldButton.kt
  core/model/build.gradle.kts
  core/model/src/main/java/com/susu/core/model/Category.kt
  core/model/src/main/java/com/susu/core/model/Ledger.kt
  core/ui/build.gradle.kts
  core/ui/src/main/java/com/susu/core/ui/extension/Json.kt
  core/ui/src/main/java/com/susu/core/ui/extension/LazyGridState.kt
  core/ui/src/main/java/com/susu/core/ui/extension/LazyListState.kt
  core/ui/src/main/res/values/strings.xml
  data/src/main/java/com/susu/data/data/di/RepositoryModule.kt
  data/src/main/java/com/susu/data/data/repository/CategoryConfigRepositoryImpl.kt
  data/src/main/java/com/susu/data/data/repository/LedgerRepositoryImpl.kt
  data/src/main/java/com/susu/data/local/RoomInMemoryDataBase.kt
  data/src/main/java/com/susu/data/local/dao/CategoryConfigDao.kt
  data/src/main/java/com/susu/data/local/di/DaoModule.kt
  data/src/main/java/com/susu/data/local/di/RoomModule.kt
  data/src/main/java/com/susu/data/local/model/CategoryConfigEntity.kt
  data/src/main/java/com/susu/data/local/model/EntityTable.kt
  data/src/main/java/com/susu/data/remote/api/CategoryService.kt
  data/src/main/java/com/susu/data/remote/api/LedgerService.kt
  data/src/main/java/com/susu/data/remote/di/ApiServiceModule.kt
  data/src/main/java/com/susu/data/remote/model/request/LedgerRequest.kt
  data/src/main/java/com/susu/data/remote/model/response/CategoryConfigResponse.kt
  data/src/main/java/com/susu/data/remote/model/response/LedgerListResponse.kt
  data/src/main/java/com/susu/data/remote/model/response/LedgerResponse.kt
  data/src/main/java/com/susu/data/remote/retrofit/ApiResult.kt
  domain/src/main/java/com/susu/domain/repository/CategoryConfigRepository.kt
  domain/src/main/java/com/susu/domain/repository/LedgerRepository.kt
  domain/src/main/java/com/susu/domain/usecase/categoryconfig/GetCategoryConfigUseCase.kt
  domain/src/main/java/com/susu/domain/usecase/ledger/DeleteLedgerUseCase.kt
  domain/src/main/java/com/susu/domain/usecase/ledger/EditLedgerUseCase.kt
  feature/navigator/src/main/java/com/susu/feature/navigator/MainActivity.kt
  feature/navigator/src/main/java/com/susu/feature/navigator/MainContract.kt
  feature/navigator/src/main/java/com/susu/feature/navigator/MainNavigator.kt
  feature/navigator/src/main/java/com/susu/feature/navigator/MainScreen.kt
  feature/navigator/src/main/java/com/susu/feature/navigator/MainViewModel.kt
  feature/navigator/src/main/res/drawable/ic_refresh.xml
  feature/received/build.gradle.kts
  feature/received/src/main/java/com/susu/feature/received/ledgerdetail/LedgerDetailContract.kt
  feature/received/src/main/java/com/susu/feature/received/ledgerdetail/LedgerDetailScreen.kt
  feature/received/src/main/java/com/susu/feature/received/ledgerdetail/LedgerDetailViewModel.kt
  feature/received/src/main/java/com/susu/feature/received/ledgeredit/LedgerEditContract.kt
  feature/received/src/main/java/com/susu/feature/received/ledgeredit/LedgerEditScreen.kt
  feature/received/src/main/java/com/susu/feature/received/ledgeredit/LedgerEditViewModel.kt
  feature/received/src/main/java/com/susu/feature/received/navigation/ReceivedNavigation.kt
  feature/received/src/main/java/com/susu/feature/received/received/ReceivedContract.kt
  feature/received/src/main/java/com/susu/feature/received/received/ReceivedScreen.kt
  feature/received/src/main/java/com/susu/feature/received/received/ReceivedViewModel.kt
  feature/received/src/main/java/com/susu/feature/received/search/LedgerSearchContract.kt
  feature/received/src/main/java/com/susu/feature/received/search/LedgerSearchScreen.kt
  feature/received/src/main/java/com/susu/feature/received/search/LedgerSearchViewModel.kt
  feature/received/src/main/res/values/strings.xml
Labels: feature, 🚨 ASAP

#70 Feature/mz 185 sent envelope add
  feature/navigator/src/main/java/com/susu/feature/navigator/MainNavigator.kt
  feature/navigator/src/main/java/com/susu/feature/navigator/MainScreen.kt
  feature/sent/src/main/java/com/susu/feature/envelopeadd/SentEnvelopeAddScreen.kt
  feature/sent/src/main/java/com/susu/feature/envelopeadd/content/DateContent.kt
  feature/sent/src/main/java/com/susu/feature/envelopeadd/content/EventContent.kt
  feature/sent/src/main/java/com/susu/feature/envelopeadd/content/MemoContent.kt
  feature/sent/src/main/java/com/susu/feature/envelopeadd/content/MoneyContent.kt
  feature/sent/src/main/java/com/susu/feature/envelopeadd/content/MoreContent.kt
  feature/sent/src/main/java/com/susu/feature/envelopeadd/content/NameContent.kt
  feature/sent/src/main/java/com/susu/feature/envelopeadd/content/PhoneContent.kt
  feature/sent/src/main/java/com/susu/feature/envelopeadd/content/PresentContent.kt
  feature/sent/src/main/java/com/susu/feature/envelopeadd/content/RelationshipContent.kt
  feature/sent/src/main/java/com/susu/feature/envelopeadd/content/VisitedContent.kt
  feature/sent/src/main/java/com/susu/feature/envelopeadd/content/component/FriendListItem.kt
  feature/sent/src/main/java/com/susu/feature/envelopeadd/content/component/SelectDateRow.kt
  feature/sent/src/main/java/com/susu/feature/sent/SentScreen.kt
  feature/sent/src/main/java/com/susu/feature/sent/navigation/SentNavigation.kt
  feature/sent/src/main/res/values/strings.xml
Labels: feature

#74 Feature/mz 194 received envelop UI
  core/designsystem/src/main/res/values/strings.xml
  core/ui/src/main/res/values/strings.xml
  feature/navigator/src/main/java/com/susu/feature/navigator/MainNavigator.kt
  feature/navigator/src/main/java/com/susu/feature/navigator/MainScreen.kt
  feature/received/src/main/java/com/susu/feature/received/envelopeadd/ReceivedEnvelopeAddScreen.kt
  feature/received/src/main/java/com/susu/feature/received/envelopeadd/content/MemoContent.kt
  feature/received/src/main/java/com/susu/feature/received/envelopeadd/content/MoneyContent.kt
  feature/received/src/main/java/com/susu/feature/received/envelopeadd/content/MoreContent.kt
  feature/received/src/main/java/com/susu/feature/received/envelopeadd/content/NameContent.kt
  feature/received/src/main/java/com/susu/feature/received/envelopeadd/content/PhoneContent.kt
  feature/received/src/main/java/com/susu/feature/received/envelopeadd/content/PresentContent.kt
  feature/received/src/main/java/com/susu/feature/received/envelopeadd/content/RelationshipContent.kt
  feature/received/src/main/java/com/susu/feature/received/envelopeadd/content/VisitedContent.kt
  feature/received/src/main/java/com/susu/feature/received/envelopeadd/content/component/FriendListItem.kt
  feature/received/src/main/java/com/susu/feature/received/ledgerdetail/LedgerDetailContract.kt
  feature/received/src/main/java/com/susu/feature/received/ledgerdetail/LedgerDetailScreen.kt
  feature/received/src/main/java/com/susu/feature/received/ledgerdetail/LedgerDetailViewModel.kt
  feature/received/src/main/java/com/susu/feature/received/navigation/ReceivedNavigation.kt
  feature/received/src/main/res/values/strings.xml
Labels: feature

#73 Feature/mz 140 mypage
  core/model/src/main/java/com/susu/core/model/SignUpUser.kt
  core/model/src/main/java/com/susu/core/model/User.kt
  core/ui/src/main/java/com/susu/core/ui/Consts.kt
  core/ui/src/main/res/drawable/ic_kakao_login.png
  core/ui/src/main/res/drawable/img_default_profile.xml
  core/ui/src/main/res/values/strings.xml
  data/src/main/java/com/susu/data/data/di/RepositoryModule.kt
  data/src/main/java/com/susu/data/data/repository/LoginRepositoryImpl.kt
  data/src/main/java/com/susu/data/data/repository/SignUpRepositoryImpl.kt
  data/src/main/java/com/susu/data/data/repository/UserRepositoryImpl.kt
  data/src/main/java/com/susu/data/remote/api/AuthService.kt
  data/src/main/java/com/susu/data/remote/api/SignUpService.kt
  data/src/main/java/com/susu/data/remote/api/UserService.kt
  data/src/main/java/com/susu/data/remote/di/ApiServiceModule.kt
  data/src/main/java/com/susu/data/remote/di/NetworkModule.kt
  data/src/main/java/com/susu/data/remote/model/SnsProviders.kt
  data/src/main/java/com/susu/data/remote/model/request/UserRequest.kt
  data/src/main/java/com/susu/data/remote/model/response/UserResponse.kt
  domain/src/main/java/com/susu/domain/repository/LoginRepository.kt
  domain/src/main/java/com/susu/domain/repository/SignUpRepository.kt
  domain/src/main/java/com/susu/domain/repository/UserRepository.kt
  domain/src/main/java/com/susu/domain/usecase/loginsignup/CheckCanRegisterUseCase.kt
  domain/src/main/java/com/susu/domain/usecase/loginsignup/LoginUseCase.kt
  domain/src/main/java/com/susu/domain/usecase/loginsignup/SignUpUseCase.kt
  domain/src/main/java/com/susu/domain/usecase/mypage/GetUserUseCase.kt
  domain/src/main/java/com/susu/domain/usecase/mypage/LogoutUseCase.kt
  domain/src/main/java/com/susu/domain/usecase/mypage/PatchUserUseCase.kt
  domain/src/main/java/com/susu/domain/usecase/mypage/WithdrawUseCase.kt
  feature/loginsignup/src/main/java/com/susu/feature/loginsignup/login/LoginScreen.kt
  feature/loginsignup/src/main/java/com/susu/feature/loginsignup/login/LoginViewModel.kt
  feature/loginsignup/src/main/java/com/susu/feature/loginsignup/signup/SignUpContract.kt
  feature/loginsignup/src/main/java/com/susu/feature/loginsignup/signup/SignUpViewModel.kt
  feature/loginsignup/src/main/java/com/susu/feature/loginsignup/signup/content/AdditionalContent.kt
  feature/mypage/src/main/java/com/susu/feature/mypage/MyPageContract.kt
  feature/mypage/src/main/java/com/susu/feature/mypage/MyPageScreen.kt
  feature/mypage/src/main/java/com/susu/feature/mypage/MyPageViewModel.kt
  feature/mypage/src/main/java/com/susu/feature/mypage/info/MyPageInfoContract.kt
  feature/mypage/src/main/java/com/susu/feature/mypage/info/MyPageInfoScreen.kt
  feature/mypage/src/main/java/com/susu/feature/mypage/info/MyPageInfoViewModel.kt
  feature/mypage/src/main/java/com/susu/feature/mypage/info/component/MyPageInfoItem.kt
  feature/mypage/src/main/java/com/susu/feature/mypage/main/MyPageContract.kt
  feature/mypage/src/main/java/com/susu/feature/mypage/main/MyPageDefaultScreen.kt
  feature/mypage/src/main/java/com/susu/feature/mypage/main/MyPageViewModel.kt
  feature/mypage/src/main/java/com/susu/feature/mypage/main/component/MyPageMenuItem.kt
  feature/mypage/src/main/java/com/susu/feature/mypage/navigation/MyPageNavigation.kt
  feature/mypage/src/main/java/com/susu/feature/mypage/social/MyPageSocialScreen.kt
  feature/mypage/src/main/res/values/strings.xml
  feature/navigator/src/main/java/com/susu/feature/navigator/MainNavigationTab.kt
  feature/navigator/src/main/java/com/susu/feature/navigator/MainNavigator.kt
  feature/navigator/src/main/java/com/susu/feature/navigator/MainScreen.kt
  feature/navigator/src/main/java/com/susu/feature/navigator/MainViewModel.kt
Labels: feature

#77 Feature/mz 195 received envelop detail UI
  core/ui/src/main/res/values/strings.xml
  feature/navigator/src/main/java/com/susu/feature/navigator/MainNavigator.kt
  feature/navigator/src/main/java/com/susu/feature/navigator/MainScreen.kt
  feature/received/src/main/java/com/susu/feature/received/envelopedetail/ReceivedEnvelopeDetailScreen.kt
  feature/received/src/main/java/com/susu/feature/received/envelopedetail/component/DetailItem.kt
  feature/received/src/main/java/com/susu/feature/received/envelopeedit/ReceivedEnvelopeEditScreen.kt
  feature/received/src/main/java/com/susu/feature/received/envelopeedit/component/EditDetailItem.kt
  feature/received/src/main/java/com/susu/feature/received/ledgerdetail/LedgerDetailContract.kt
  feature/received/src/main/java/com/susu/feature/received/ledgerdetail/LedgerDetailScreen.kt
  feature/received/src/main/java/com/susu/feature/received/ledgerdetail/LedgerDetailViewModel.kt
  feature/received/src/main/java/com/susu/feature/received/navigation/ReceivedNavigation.kt
  feature/received/src/main/res/values/strings.xml
Labels: feature

#79 Feature/mz 182 ledger add
  core/designsystem/src/main/java/com/susu/core/designsystem/component/bottomsheet/datepicker/SusuDatePickerBottomSheet.kt
  core/designsystem/src/main/java/com/susu/core/designsystem/component/button/BasicButton.kt
  core/designsystem/src/main/java/com/susu/core/designsystem/component/button/SusuGhostButton.kt
  core/designsystem/src/main/java/com/susu/core/designsystem/component/textfieldbutton/SusuTextFieldButton.kt
  core/ui/src/main/java/com/susu/core/ui/util/Date.kt
  core/ui/src/main/res/values/strings.xml
  data/src/main/java/com/susu/data/data/repository/LedgerRepositoryImpl.kt
  data/src/main/java/com/susu/data/remote/api/LedgerService.kt
  domain/src/main/java/com/susu/domain/repository/LedgerRepository.kt
  domain/src/main/java/com/susu/domain/usecase/ledger/CreateLedgerUseCase.kt
  feature/received/src/main/java/com/susu/feature/received/ledgeradd/LedgerAddContract.kt
  feature/received/src/main/java/com/susu/feature/received/ledgeradd/LedgerAddScreen.kt
  feature/received/src/main/java/com/susu/feature/received/ledgeradd/LedgerAddViewModel.kt
  feature/received/src/main/java/com/susu/feature/received/ledgeradd/content/CategoryContent.kt
  feature/received/src/main/java/com/susu/feature/received/ledgeradd/content/DateContent.kt
  feature/received/src/main/java/com/susu/feature/received/ledgeradd/content/category/CategoryContent.kt
  feature/received/src/main/java/com/susu/feature/received/ledgeradd/content/category/CategoryContract.kt
  feature/received/src/main/java/com/susu/feature/received/ledgeradd/content/category/CategoryViewModel.kt
  feature/received/src/main/java/com/susu/feature/received/ledgeradd/content/date/DateContent.kt
  feature/received/src/main/java/com/susu/feature/received/ledgeradd/content/date/DateContract.kt
  feature/received/src/main/java/com/susu/feature/received/ledgeradd/content/date/DateViewModel.kt
  feature/received/src/main/java/com/susu/feature/received/ledgeradd/content/date/component/SelectDateRow.kt
  feature/received/src/main/java/com/susu/feature/received/ledgeradd/content/name/NameContent.kt
  feature/received/src/main/java/com/susu/feature/received/ledgeradd/content/name/NameContract.kt
  feature/received/src/main/java/com/susu/feature/received/ledgeradd/content/name/NameViewModel.kt
  feature/received/src/main/java/com/susu/feature/received/ledgeredit/LedgerEditScreen.kt
  feature/received/src/main/java/com/susu/feature/received/navigation/ReceivedNavigation.kt
  feature/received/src/main/java/com/susu/feature/received/received/ReceivedScreen.kt
  feature/received/src/main/java/com/susu/feature/received/received/ReceivedViewModel.kt
  feature/received/src/main/java/com/susu/feature/received/search/LedgerSearchContract.kt
  feature/received/src/main/java/com/susu/feature/received/search/LedgerSearchScreen.kt
  feature/received/src/main/java/com/susu/feature/received/search/LedgerSearchViewModel.kt
  feature/received/src/main/res/values/strings.xml
Labels: feature

#85 Feature/mz 181 ledger filter
  core/designsystem/src/main/java/com/susu/core/designsystem/component/button/FilterButton.kt
  core/designsystem/src/main/java/com/susu/core/designsystem/component/button/RefreshButton.kt
  core/designsystem/src/main/java/com/susu/core/designsystem/component/button/SelectedFilterButton.kt
  core/designsystem/src/main/res/values/strings.xml
  core/ui/src/main/java/com/susu/core/ui/extension/Flow.kt
  core/ui/src/main/java/com/susu/core/ui/extension/LazyGridState.kt
  core/ui/src/main/res/values/strings.xml
  data/src/main/java/com/susu/data/data/repository/LedgerRepositoryImpl.kt
  data/src/main/java/com/susu/data/remote/api/LedgerService.kt
  domain/src/main/java/com/susu/domain/repository/LedgerRepository.kt
  domain/src/main/java/com/susu/domain/usecase/ledger/GetLedgerListUseCase.kt
  feature/navigator/src/main/java/com/susu/feature/navigator/MainNavigator.kt
  feature/navigator/src/main/java/com/susu/feature/navigator/MainScreen.kt
  feature/navigator/src/main/res/values/strings.xml
  feature/received/build.gradle.kts
  feature/received/src/main/java/com/susu/feature/received/ledgeredit/LedgerEditScreen.kt
  feature/received/src/main/java/com/susu/feature/received/ledgeredit/LedgerEditViewModel.kt
  feature/received/src/main/java/com/susu/feature/received/ledgerfilter/LedgerFilterContract.kt
  feature/received/src/main/java/com/susu/feature/received/ledgerfilter/LedgerFilterScreen.kt
  feature/received/src/main/java/com/susu/feature/received/ledgerfilter/LedgerFilterViewModel.kt
  feature/received/src/main/java/com/susu/feature/received/ledgerfilter/component/DateText.kt
  feature/received/src/main/java/com/susu/feature/received/navigation/ReceivedNavigation.kt
  feature/received/src/main/java/com/susu/feature/received/navigation/argument/FilterArgument.kt
  feature/received/src/main/java/com/susu/feature/received/received/ReceivedContract.kt
  feature/received/src/main/java/com/susu/feature/received/received/ReceivedScreen.kt
  feature/received/src/main/java/com/susu/feature/received/received/ReceivedViewModel.kt
  feature/received/src/main/java/com/susu/feature/received/received/component/LedgerCategoryCard.kt
  feature/received/src/main/res/values/strings.xml
  gradle/libs.versions.toml
Labels: feature

#88 Feature/datepicker-click SusuDatePicker 클릭으로 선택
  core/designsystem/src/main/java/com/susu/core/designsystem/component/bottomsheet/datepicker/InfiniteColumn.kt
  core/designsystem/src/main/java/com/susu/core/designsystem/component/bottomsheet/datepicker/SusuDatePickerBottomSheet.kt
Labels: feature

#89 Feature/mz 134 vote add
  core/designsystem/src/main/java/com/susu/core/designsystem/component/appbar/icon/RegisterText.kt
  core/designsystem/src/main/java/com/susu/core/designsystem/component/button/ClearIconButton.kt
  core/designsystem/src/main/java/com/susu/core/designsystem/component/textfieldbutton/SusuTextFieldButton.kt
  core/designsystem/src/main/java/com/susu/core/designsystem/component/textfieldbutton/TextFieldButtonColor.kt
  core/designsystem/src/main/res/drawable/ic_clear.xml
  core/model/src/main/java/com/susu/core/model/Vote.kt
  core/ui/src/main/res/values/strings.xml
  data/src/main/java/com/susu/data/data/di/RepositoryModule.kt
  data/src/main/java/com/susu/data/data/repository/VoteRepositoryImpl.kt
  data/src/main/java/com/susu/data/remote/api/VoteService.kt
  data/src/main/java/com/susu/data/remote/di/ApiServiceModule.kt
  data/src/main/java/com/susu/data/remote/model/request/CreateVoteRequest.kt
  data/src/main/java/com/susu/data/remote/model/response/VoteResponse.kt
  domain/src/main/java/com/susu/domain/repository/VoteRepository.kt
  domain/src/main/java/com/susu/domain/usecase/vote/CreateVoteUseCase.kt
  feature/community/src/main/java/com/susu/feature/community/CommunityScreen.kt
  feature/community/src/main/java/com/susu/feature/community/navigation/CommunityNavigation.kt
  feature/community/src/main/java/com/susu/feature/community/voteadd/VoteAddContract.kt
  feature/community/src/main/java/com/susu/feature/community/voteadd/VoteAddScreen.kt
  feature/community/src/main/java/com/susu/feature/community/voteadd/VoteAddViewModel.kt
  feature/community/src/main/res/values/strings.xml
  feature/navigator/src/main/java/com/susu/feature/navigator/MainNavigator.kt
  feature/navigator/src/main/java/com/susu/feature/navigator/MainScreen.kt
Labels: feature

#91 Feature/mz 199 마이페이지 - 내정보 편집, 앱 버전
  core/designsystem/src/main/java/com/susu/core/designsystem/component/bottomsheet/datepicker/SusuDatePickerBottomSheet.kt
  core/designsystem/src/main/res/values/strings.xml
  core/ui/src/main/java/com/susu/core/ui/Consts.kt
  core/ui/src/main/res/values/strings.xml
  feature/mypage/src/main/java/com/susu/feature/mypage/MyPagePrivacyPolicyScreen.kt
  feature/mypage/src/main/java/com/susu/feature/mypage/info/MyPageInfoContract.kt
  feature/mypage/src/main/java/com/susu/feature/mypage/info/MyPageInfoScreen.kt
  feature/mypage/src/main/java/com/susu/feature/mypage/info/MyPageInfoViewModel.kt
  feature/mypage/src/main/java/com/susu/feature/mypage/info/component/MyPageInfoItem.kt
  feature/mypage/src/main/java/com/susu/feature/mypage/main/MyPageDefaultScreen.kt
  feature/mypage/src/main/java/com/susu/feature/mypage/main/component/MyPageMenuItem.kt
  feature/mypage/src/main/java/com/susu/feature/mypage/navigation/MyPageNavigation.kt
  feature/mypage/src/main/java/com/susu/feature/mypage/social/MyPageSocialScreen.kt
  feature/mypage/src/main/res/values/strings.xml
  feature/navigator/src/main/java/com/susu/feature/navigator/MainNavigator.kt
  feature/navigator/src/main/java/com/susu/feature/navigator/MainScreen.kt
Labels: feature

#92 Feature/mz 201 vote list UI
  core/designsystem/src/main/java/com/susu/core/designsystem/component/button/BasicButton.kt
  core/designsystem/src/main/java/com/susu/core/designsystem/component/button/SusuFilledButton.kt
  core/designsystem/src/main/java/com/susu/core/designsystem/component/button/SusuFloatingButton.kt
  core/designsystem/src/main/java/com/susu/core/designsystem/component/button/SusuGhostButton.kt
  core/designsystem/src/main/java/com/susu/core/designsystem/component/button/SusuLinedButton.kt
  core/ui/src/main/res/values/strings.xml
  feature/community/src/main/java/com/susu/feature/community/CommunityScreen.kt
  feature/community/src/main/java/com/susu/feature/community/community/CommunityScreen.kt
  feature/community/src/main/java/com/susu/feature/community/community/component/MostPopularVoteCard.kt
  feature/community/src/main/java/com/susu/feature/community/community/component/VoteCard.kt
  feature/community/src/main/java/com/susu/feature/community/navigation/CommunityNavigation.kt
  feature/community/src/main/res/drawable/ic_report.xml
  feature/community/src/main/res/drawable/ic_uncheck.xml
  feature/community/src/main/res/drawable/ic_vote.xml
  feature/community/src/main/res/drawable/ic_vote_add.xml
  feature/community/src/main/res/values/strings.xml
  feature/navigator/src/main/java/com/susu/feature/navigator/MainNavigator.kt
Labels: feature

#94 Feature/mz 129 my statistics
  core/model/src/main/java/com/susu/core/model/MyStatistics.kt
  core/model/src/main/java/com/susu/core/model/StatisticsElement.kt
  core/ui/src/main/res/values/strings.xml
  data/src/main/java/com/susu/data/data/di/RepositoryModule.kt
  data/src/main/java/com/susu/data/data/repository/StatisticsRepositoryImpl.kt
  data/src/main/java/com/susu/data/data/repository/UserRepositoryImpl.kt
  data/src/main/java/com/susu/data/remote/api/StatisticsService.kt
  data/src/main/java/com/susu/data/remote/di/ApiServiceModule.kt
  data/src/main/java/com/susu/data/remote/model/response/MyStatisticsResponse.kt
  domain/src/main/java/com/susu/domain/repository/StatisticsRepository.kt
  domain/src/main/java/com/susu/domain/usecase/statistics/CheckAdditionalUserInfoUseCase.kt
  domain/src/main/java/com/susu/domain/usecase/statistics/GetMyStatisticsUseCase.kt
  feature/mypage/src/main/java/com/susu/feature/mypage/info/MyPageInfoScreen.kt
  feature/mypage/src/main/java/com/susu/feature/mypage/info/MyPageInfoViewModel.kt
  feature/navigator/src/main/java/com/susu/feature/navigator/MainScreen.kt
  feature/statistics/src/main/java/com/susu/feature/statistics/StatisticsContract.kt
  feature/statistics/src/main/java/com/susu/feature/statistics/StatisticsScreen.kt
  feature/statistics/src/main/java/com/susu/feature/statistics/StatisticsViewModel.kt
  feature/statistics/src/main/java/com/susu/feature/statistics/component/RecentSpentGraph.kt
  feature/statistics/src/main/java/com/susu/feature/statistics/component/StatisticsItem.kt
  feature/statistics/src/main/java/com/susu/feature/statistics/component/StatisticsTab.kt
  feature/statistics/src/main/java/com/susu/feature/statistics/content/MyStatisticsContent.kt
  feature/statistics/src/main/java/com/susu/feature/statistics/content/MyStatisticsContract.kt
  feature/statistics/src/main/java/com/susu/feature/statistics/content/MyStatisticsViewModel.kt
  feature/statistics/src/main/java/com/susu/feature/statistics/navigation/StatisticsNavigation.kt
  feature/statistics/src/main/res/values/strings.xml
Labels: feature, 🚨 ASAP

#95 feat: 투표 상세 ui
  feature/community/src/main/java/com/susu/feature/community/votedetail/VoteDetailScreen.kt
  feature/community/src/main/java/com/susu/feature/community/votedetail/component/VoteItem.kt
  feature/community/src/main/res/drawable/ic_vote_check.xml
  feature/community/src/main/res/values/strings.xml
Labels: feature

#101 Feature/mz 203 vote list api
  core/model/src/main/java/com/susu/core/model/Vote.kt
  core/ui/src/main/java/com/susu/core/ui/extension/LazyListState.kt
  core/ui/src/main/java/com/susu/core/ui/util/Date.kt
  core/ui/src/main/res/values/strings.xml
  data/src/main/java/com/susu/data/data/repository/VoteRepositoryImpl.kt
  data/src/main/java/com/susu/data/remote/api/VoteService.kt
  data/src/main/java/com/susu/data/remote/model/request/CreateVoteRequest.kt
  data/src/main/java/com/susu/data/remote/model/response/PopularVoteResponse.kt
  data/src/main/java/com/susu/data/remote/model/response/PostCategoryConfig.kt
  data/src/main/java/com/susu/data/remote/model/response/VoteListResponse.kt
  data/src/main/java/com/susu/data/remote/model/response/VoteResponse.kt
  domain/src/main/java/com/susu/domain/repository/VoteRepository.kt
  domain/src/main/java/com/susu/domain/usecase/ledger/GetLedgerListUseCase.kt
  domain/src/main/java/com/susu/domain/usecase/vote/GetPopularVoteListUseCase.kt
  domain/src/main/java/com/susu/domain/usecase/vote/GetPostCategoryConfigUseCase.kt
  domain/src/main/java/com/susu/domain/usecase/vote/GetVoteListUseCase.kt
  feature/community/build.gradle.kts
  feature/community/src/main/java/com/susu/feature/community/community/CommunityContract.kt
  feature/community/src/main/java/com/susu/feature/community/community/CommunityScreen.kt
  feature/community/src/main/java/com/susu/feature/community/community/CommunityViewModel.kt
  feature/community/src/main/java/com/susu/feature/community/community/component/MostPopularVoteCard.kt
  feature/community/src/main/java/com/susu/feature/community/community/component/VoteCard.kt
  feature/community/src/main/java/com/susu/feature/community/navigation/CommunityNavigation.kt
  feature/community/src/main/java/com/susu/feature/community/voteadd/VoteAddContract.kt
  feature/community/src/main/java/com/susu/feature/community/voteadd/VoteAddScreen.kt
  feature/community/src/main/java/com/susu/feature/community/voteadd/VoteAddViewModel.kt
  feature/community/src/main/res/values/strings.xml
  feature/navigator/src/main/java/com/susu/feature/navigator/MainScreen.kt
  feature/received/src/main/java/com/susu/feature/received/received/ReceivedViewModel.kt
Labels: feature

#103 Feature/mz 207 vote detail api
  core/model/src/main/java/com/susu/core/model/Vote.kt
  data/src/main/java/com/susu/data/data/repository/VoteRepositoryImpl.kt
  data/src/main/java/com/susu/data/remote/api/VoteService.kt
  data/src/main/java/com/susu/data/remote/model/request/CreateVoteRequest.kt
  data/src/main/java/com/susu/data/remote/model/request/VoteRequest.kt
  data/src/main/java/com/susu/data/remote/model/response/PopularVoteResponse.kt
  data/src/main/java/com/susu/data/remote/model/response/VoteDetailResponse.kt
  data/src/main/java/com/susu/data/remote/model/response/VoteResponse.kt
  domain/src/main/java/com/susu/domain/repository/VoteRepository.kt
  domain/src/main/java/com/susu/domain/usecase/vote/GetVoteDetailUseCase.kt
  domain/src/main/java/com/susu/domain/usecase/vote/VoteUseCase.kt
  feature/community/src/main/java/com/susu/feature/community/community/CommunityContract.kt
  feature/community/src/main/java/com/susu/feature/community/community/CommunityScreen.kt
  feature/community/src/main/java/com/susu/feature/community/community/CommunityViewModel.kt
  feature/community/src/main/java/com/susu/feature/community/community/component/MostPopularVoteCard.kt
  feature/community/src/main/java/com/susu/feature/community/community/component/VoteCard.kt
  feature/community/src/main/java/com/susu/feature/community/navigation/CommunityNavigation.kt
  feature/community/src/main/java/com/susu/feature/community/votedetail/VoteDetailContract.kt
  feature/community/src/main/java/com/susu/feature/community/votedetail/VoteDetailScreen.kt
  feature/community/src/main/java/com/susu/feature/community/votedetail/VoteDetailViewModel.kt
  feature/community/src/main/java/com/susu/feature/community/votedetail/component/VoteItem.kt
  feature/community/src/main/res/values/strings.xml
  feature/navigator/src/main/java/com/susu/feature/navigator/MainNavigator.kt
  feature/navigator/src/main/java/com/susu/feature/navigator/MainScreen.kt
Labels: feature, 🚨 ASAP

#104 Feature/mz 123 received envelope list api
  core/model/src/main/java/com/susu/core/model/Envelope.kt
  core/model/src/main/java/com/susu/core/model/Friend.kt
  core/model/src/main/java/com/susu/core/model/Relationship.kt
  core/model/src/main/java/com/susu/core/model/SearchEnvelope.kt
  core/ui/src/main/res/values/strings.xml
  data/src/main/java/com/susu/data/data/repository/EnvelopesRepositoryImpl.kt
  data/src/main/java/com/susu/data/data/repository/FriendRepositoryImpl.kt
  data/src/main/java/com/susu/data/data/repository/LedgerRepositoryImpl.kt
  data/src/main/java/com/susu/data/remote/api/EnvelopesService.kt
  data/src/main/java/com/susu/data/remote/api/LedgerService.kt
  data/src/main/java/com/susu/data/remote/model/request/FriendRequest.kt
  data/src/main/java/com/susu/data/remote/model/response/CreateEnvelopeResponse.kt
  data/src/main/java/com/susu/data/remote/model/response/EnvelopeResponse.kt
  data/src/main/java/com/susu/data/remote/model/response/FriendSearchResponse.kt
  data/src/main/java/com/susu/data/remote/model/response/RelationShipListResponse.kt
  data/src/main/java/com/susu/data/remote/model/response/SearchEnvelopeResponse.kt
  domain/src/main/java/com/susu/domain/repository/EnvelopesRepository.kt
  domain/src/main/java/com/susu/domain/repository/FriendRepository.kt
  domain/src/main/java/com/susu/domain/repository/LedgerRepository.kt
  domain/src/main/java/com/susu/domain/usecase/envelope/CreateReceivedEnvelopeUseCase.kt
  domain/src/main/java/com/susu/domain/usecase/envelope/SearchReceivedEnvelopeListUseCase.kt
  domain/src/main/java/com/susu/domain/usecase/ledger/GetLedgerUseCase.kt
  feature/navigator/src/main/java/com/susu/feature/navigator/MainScreen.kt
  feature/received/src/main/java/com/susu/feature/received/envelopeadd/ReceivedEnvelopeAddContract.kt
  feature/received/src/main/java/com/susu/feature/received/envelopeadd/ReceivedEnvelopeAddScreen.kt
  feature/received/src/main/java/com/susu/feature/received/envelopeadd/ReceivedEnvelopeAddViewModel.kt
  feature/received/src/main/java/com/susu/feature/received/ledgerdetail/LedgerDetailContract.kt
  feature/received/src/main/java/com/susu/feature/received/ledgerdetail/LedgerDetailScreen.kt
  feature/received/src/main/java/com/susu/feature/received/ledgerdetail/LedgerDetailViewModel.kt
  feature/received/src/main/java/com/susu/feature/received/ledgerdetail/component/LedgerDetailEnvelopeContainer.kt
  feature/received/src/main/java/com/susu/feature/received/ledgeredit/LedgerEditContract.kt
  feature/received/src/main/java/com/susu/feature/received/ledgeredit/LedgerEditScreen.kt
  feature/received/src/main/java/com/susu/feature/received/ledgeredit/LedgerEditViewModel.kt
  feature/received/src/main/java/com/susu/feature/received/navigation/ReceivedNavigation.kt
  feature/received/src/main/java/com/susu/feature/received/received/ReceivedViewModel.kt
Labels: feature, 🚨 ASAP

#105 Feature/mz 119 보낸 봉투 생성
  domain/src/main/java/com/susu/domain/usecase/envelope/CreateSentEnvelopeUseCase.kt
  feature/navigator/src/main/java/com/susu/feature/navigator/MainScreen.kt
  feature/received/src/main/java/com/susu/feature/received/ledgerdetail/LedgerDetailScreen.kt
  feature/sent/src/main/java/com/susu/feature/envelopeadd/EnvelopeAddContract.kt
  feature/sent/src/main/java/com/susu/feature/envelopeadd/EnvelopeAddViewModel.kt
  feature/sent/src/main/java/com/susu/feature/envelopeadd/SentEnvelopeAddScreen.kt
  feature/sent/src/main/java/com/susu/feature/envelopeadd/content/DateContent.kt
  feature/sent/src/main/java/com/susu/feature/envelopeadd/content/MemoContent.kt
  feature/sent/src/main/java/com/susu/feature/envelopeadd/content/MoreContent.kt
  feature/sent/src/main/java/com/susu/feature/envelopeadd/content/RelationshipContent.kt
  feature/sent/src/main/java/com/susu/feature/envelopeadd/content/VisitedContent.kt
  feature/sent/src/main/java/com/susu/feature/envelopeadd/content/category/CategoryContent.kt
  feature/sent/src/main/java/com/susu/feature/envelopeadd/content/category/CategoryContract.kt
  feature/sent/src/main/java/com/susu/feature/envelopeadd/content/category/CategoryViewModel.kt
  feature/sent/src/main/java/com/susu/feature/envelopeadd/content/component/FriendListItem.kt
  feature/sent/src/main/java/com/susu/feature/envelopeadd/content/date/DateContent.kt
  feature/sent/src/main/java/com/susu/feature/envelopeadd/content/date/DateContract.kt
  feature/sent/src/main/java/com/susu/feature/envelopeadd/content/date/DateViewModel.kt
  feature/sent/src/main/java/com/susu/feature/envelopeadd/content/memo/MemoContent.kt
  feature/sent/src/main/java/com/susu/feature/envelopeadd/content/memo/MemoContract.kt
  feature/sent/src/main/java/com/susu/feature/envelopeadd/content/memo/MemoViewModel.kt
  feature/sent/src/main/java/com/susu/feature/envelopeadd/content/money/MoneyContent.kt
  feature/sent/src/main/java/com/susu/feature/envelopeadd/content/money/MoneyContract.kt
  feature/sent/src/main/java/com/susu/feature/envelopeadd/content/money/MoneyViewModel.kt
  feature/sent/src/main/java/com/susu/feature/envelopeadd/content/more/MoreContent.kt
  feature/sent/src/main/java/com/susu/feature/envelopeadd/content/more/MoreContract.kt
  feature/sent/src/main/java/com/susu/feature/envelopeadd/content/more/MoreViewModel.kt
  feature/sent/src/main/java/com/susu/feature/envelopeadd/content/name/NameContent.kt
  feature/sent/src/main/java/com/susu/feature/envelopeadd/content/name/NameContract.kt
  feature/sent/src/main/java/com/susu/feature/envelopeadd/content/name/NameViewModel.kt
  feature/sent/src/main/java/com/susu/feature/envelopeadd/content/phone/PhoneContent.kt
  feature/sent/src/main/java/com/susu/feature/envelopeadd/content/phone/PhoneContract.kt
  feature/sent/src/main/java/com/susu/feature/envelopeadd/content/phone/PhoneViewModel.kt
  feature/sent/src/main/java/com/susu/feature/envelopeadd/content/present/PresentContent.kt
  feature/sent/src/main/java/com/susu/feature/envelopeadd/content/present/PresentContract.kt
  feature/sent/src/main/java/com/susu/feature/envelopeadd/content/present/PresentViewModel.kt
  feature/sent/src/main/java/com/susu/feature/envelopeadd/content/relationship/RelationshipContent.kt
  feature/sent/src/main/java/com/susu/feature/envelopeadd/content/relationship/RelationshipContract.kt
  feature/sent/src/main/java/com/susu/feature/envelopeadd/content/relationship/RelationshipViewModel.kt
  feature/sent/src/main/java/com/susu/feature/envelopeadd/content/visited/VisitedContent.kt
  feature/sent/src/main/java/com/susu/feature/envelopeadd/content/visited/VisitedContract.kt
  feature/sent/src/main/java/com/susu/feature/envelopeadd/content/visited/VisitedViewModel.kt
  feature/sent/src/main/java/com/susu/feature/sent/navigation/SentNavigation.kt
  feature/sent/src/main/res/values/strings.xml
Labels: feature

#108 Feature/mz 219 check dialog 컴포넌트
  core/designsystem/src/main/java/com/susu/core/designsystem/component/dialog/SusuCheckedDialog.kt
  core/designsystem/src/main/java/com/susu/core/designsystem/component/util/CheckCircle.kt
  core/designsystem/src/main/res/drawable/ic_check_circle_background.xml
  core/ui/src/main/java/com/susu/core/ui/DialogToken.kt
  feature/loginsignup/src/main/java/com/susu/feature/loginsignup/signup/content/TermsContent.kt
  feature/navigator/src/main/java/com/susu/feature/navigator/MainScreen.kt
Labels: feature

#113 Feature/mz 197 received envelop edit delete, 장부 그룹핑 제거
  core/model/src/main/java/com/susu/core/model/Envelope.kt
  core/model/src/main/java/com/susu/core/model/Friend.kt
  core/ui/src/main/java/com/susu/core/ui/extension/Long.kt
  core/ui/src/main/java/com/susu/core/ui/util/Date.kt
  core/ui/src/main/res/values/strings.xml
  data/src/main/java/com/susu/data/data/repository/EnvelopesRepositoryImpl.kt
  data/src/main/java/com/susu/data/data/repository/FriendRepositoryImpl.kt
  data/src/main/java/com/susu/data/remote/api/FriendService.kt
  data/src/main/java/com/susu/data/remote/model/response/EnvelopeResponse.kt
  domain/src/main/java/com/susu/domain/repository/EnvelopesRepository.kt
  domain/src/main/java/com/susu/domain/repository/FriendRepository.kt
  domain/src/main/java/com/susu/domain/usecase/envelope/EditReceivedEnvelopeUseCase.kt
  feature/navigator/src/main/java/com/susu/feature/navigator/MainNavigator.kt
  feature/received/src/main/java/com/susu/feature/received/envelopedetail/ReceivedEnvelopeDetailContract.kt
  feature/received/src/main/java/com/susu/feature/received/envelopedetail/ReceivedEnvelopeDetailScreen.kt
  feature/received/src/main/java/com/susu/feature/received/envelopedetail/ReceivedEnvelopeDetailViewModel.kt
  feature/received/src/main/java/com/susu/feature/received/envelopeedit/ReceivedEnvelopeEditContract.kt
  feature/received/src/main/java/com/susu/feature/received/envelopeedit/ReceivedEnvelopeEditScreen.kt
  feature/received/src/main/java/com/susu/feature/received/envelopeedit/ReceivedEnvelopeEditViewModel.kt
  feature/received/src/main/java/com/susu/feature/received/ledgerdetail/LedgerDetailContract.kt
  feature/received/src/main/java/com/susu/feature/received/ledgerdetail/LedgerDetailScreen.kt
  feature/received/src/main/java/com/susu/feature/received/ledgerdetail/LedgerDetailViewModel.kt
  feature/received/src/main/java/com/susu/feature/received/navigation/ReceivedNavigation.kt
  feature/received/src/main/java/com/susu/feature/received/received/ReceivedScreen.kt
  feature/received/src/main/java/com/susu/feature/received/received/component/LedgerCategoryCard.kt
Labels: feature, 🚨 ASAP
